import type { MetadataRoute } from "next";

/**
 * Web app manifest, generated by Next so it is typed and stays in step with the
 * app's metadata rather than drifting as a hand-maintained JSON file.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Focus Log",
    short_name: "Focus Log",
    description: "A private ledger of attention.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#0b0a09",
    theme_color: "#0b0a09",
    orientation: "portrait-primary",
    categories: ["productivity", "utilities"],
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable variants keep the mark inside the safe zone so Android's
      // adaptive masks cannot crop it.
      { src: "/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    shortcuts: [
      { name: "Today", url: "/", description: "Start or resume a focus session" },
      { name: "Insights", url: "/stats", description: "See where your attention went" },
    ],
  };
}
